# Generated by Django 5.1.4 on 2024-12-14 03:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('quiz_backend', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='quizsession',
            name='current_question_index',
            field=models.IntegerField(default=0),
        ),
    ]
